name: Pushing to all live branches

on:
  push:
    branches:
      - staging
    paths-ignore:
      - 'templates/**'
      - 'config/**'
      
  pull_request:
    branches:
      - 'master'
    
jobs:
  build:
    # needs: nothing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pushes to all sites
        run: |
          git checkout master
          git pull
          git checkout -b live/UK
          git push -f --set-upstream origin live/UK
          git checkout -b live/US
          git push -f --set-upstream origin live/US
          git checkout -b live/IE
          git push -f --set-upstream origin live/IE
