name: Pushing to all live branches

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'templates/**'      
jobs:
  build:
    # needs: nothing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pushes to all sites
        run: |
          git config user.email "mattymozzah@gmail.com"
          git config user.name "matthewgelder"
          git checkout master
          git pull
          git checkout -b live/UK
          git merge master
          git push -f --set-upstream origin live/UK
          git checkout -b live/US
          git merge master
          git push -f --set-upstream origin live/US
          git checkout -b live/IE
          git merge master
          git push -f --set-upstream origin live/IE
